---
title: "WaterPlots"
author: "jiml"
date: "2024-06-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required packages and functions.

```{r,warning=FALSE, include=FALSE}
# -- REQUIRED PACKAGES -------------------------------------------------------

packages <- c("tidyverse","ggplot2","ggtext","janitor",
              "plotly", "viridis","rstudioapi")

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

 #-- FUNCTIONS ---------------------------------------------------------------
source("./R/importCSdata.r")

```
# Reading in the rds data file

```{r}

 df_logger <- read_rds(file =  rstudioapi::selectFile(caption = "Select logger data rds file",
                                       filter = "rds files (*.rds)"))
# _______________________________________________________________________________

```
# Remove bad data.

```{r}
# remove -7999 which is Campbell's missing data value
  df_logger <- df_logger %>% mutate(across(where(is.numeric), ~na_if(.,-7999))) 

#Other data issues


```
# Plot data
## - Setup the parameters for ggplotly
```{r}
# set the min and max for the initial x axis display in ggplotly
max_date <- max(df_logger$timestamp)
min_date <- max_date - lubridate::days(5) 

# ---- Setting up interactive plots with ggplotly-------
# Note for rangeslider to work:
# the dynamicTicks needs to be true for the buttons to show
# autorange needs to be FALSE for range to work

# Define xaxis options for using a range slider
xax<- list( 
  autorange=F,
  range= list(min_date, max_date),
  rangeselector = list(
    buttons = list(
      list(count = 1, label = "1 week", strp ="week", stepmode = "backward"),
      list(count = 3, label = "3 mo", step = "month", stepmode = "backward"),
      list(count = 6, label = "6 mo", step = "month", stepmode = "backward"),
      list(count = 1, label = "YTD", step = "year", stepmode = "todate"),
      list(step = "all")
    )),
  rangeslider = list(type = "date", thickness=0.05))
# define zoom for y axis
yax <- list(fixedrange = FALSE,zerolinewidth = .1)

# Create a list of arguments for the annotation layout to add titles to the subplots
anno_agr <-list(x = .5,
                text = "",
                y = 1,
                yref = "paper",
                xref = "paper",
                xanchor = "center",
                yanchor = "top",
                yshift = 20,
                showarrow = FALSE,
                font = list(size = 15))
```
## - Plot soil Tempertures

``` {r}
  
sp1 <- ggplotly(
  df_logger %>% select(timestamp, contains("avg")  & -contains("battery")) %>%                                                
  pivot_longer(-timestamp, names_to = "key", values_to = "value", values_drop_na = TRUE) %>%
  ggplot(data=.,aes(x=timestamp, y = value,color=key)) +
  scale_x_datetime()+
  coord_cartesian(ylim = c(-15,15)) +
  labs(title ="Soil Temperatures and Moisture",
       x = "Date",
       y = "Celsius ",
       color = 'Legend')+
  #scale_color_manual(values = pal1)+
  theme_bw() +
  geom_line(aes(color = key),linewidth = .3) +
  theme(
    plot.title = element_text(hjust = 0.7)
  ),
  dynamicTicks = T) %>% 
    layout(xaxis= xax,
         yaxis =yax,
         annotations = anno_agr) %>% 
  partial_bundle()
sp1
```
 #- Soil moisture plots
 
``` {r}
 
 sp2 <- ggplotly(
 df_logger %>% select(timestamp,contains("Moisture")) %>%
  gather("key", "value", -timestamp) %>%
  ggplot(data=., aes(x=timestamp, y = value, color = key)) +
  scale_x_datetime()+
  labs(x = "Date",
       y = "Percent(VW)",
       color = 'Legend')+
  coord_cartesian(ylim = c(0,NA)) +
  #scale_color_manual(values = pal1)+
  theme_bw() +
  geom_line(aes(color = key),linewidth = .3) 
,
  dynamicTicks = T) %>% 
    layout(xaxis= xax,
         yaxis =list(zerolinewidth = .1,yax),
         annotations = anno_agr) %>% 
  partial_bundle()
sp2

```